/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.shansbookinventory;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author nano
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public static String name, role;

    public MainMenu() {
        initComponents();

    }

    public MainMenu(String name, String role) {
        initComponents();
        this.name = name;
        this.role = role;
        customize();

    }

    void customize() {
        lblName.setText(name);
        lblRole.setText(role);

        if (!(role.equals("Admin"))) {
            lblManageUsers.setVisible(false);
            lblSalesReport.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblManageUsers = new javax.swing.JLabel();
        lblManageSuppliers = new javax.swing.JLabel();
        lblManageCustomers = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblProductsAndPurchases = new javax.swing.JLabel();
        lblSales = new javax.swing.JLabel();
        lblSalesReport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Shans Book Store");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(51, 51, 255));
        lblName.setText("lblName");

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRole.setForeground(new java.awt.Color(51, 51, 255));
        lblRole.setText("lblRole");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblManageUsers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblManageUsers.setForeground(new java.awt.Color(51, 102, 255));
        lblManageUsers.setText("Manage Users");
        lblManageUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblManageUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManageUsersMouseExited(evt);
            }
        });

        lblManageSuppliers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblManageSuppliers.setForeground(new java.awt.Color(51, 102, 255));
        lblManageSuppliers.setText("Manage Suppliers");
        lblManageSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageSuppliersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblManageSuppliersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManageSuppliersMouseExited(evt);
            }
        });

        lblManageCustomers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblManageCustomers.setForeground(new java.awt.Color(51, 102, 255));
        lblManageCustomers.setText("Manage Customers");
        lblManageCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageCustomersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblManageCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManageCustomersMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Logout");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        lblProductsAndPurchases.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblProductsAndPurchases.setForeground(new java.awt.Color(51, 102, 255));
        lblProductsAndPurchases.setText("Products & Purchases");
        lblProductsAndPurchases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductsAndPurchasesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProductsAndPurchasesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProductsAndPurchasesMouseExited(evt);
            }
        });

        lblSales.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSales.setForeground(new java.awt.Color(51, 102, 255));
        lblSales.setText("Sales");
        lblSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalesMouseExited(evt);
            }
        });

        lblSalesReport.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSalesReport.setForeground(new java.awt.Color(51, 102, 255));
        lblSalesReport.setText("Sales Report");
        lblSalesReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalesReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalesReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalesReportMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSales, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProductsAndPurchases, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                .addGap(110, 110, 110)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManageSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManageCustomers))
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductsAndPurchases)
                    .addComponent(lblManageSuppliers))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSales)
                    .addComponent(lblManageCustomers))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalesReport)
                    .addComponent(lblManageUsers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblRole)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(18, 18, 18)
                        .addComponent(lblRole))
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblManageUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageUsersMouseClicked
        new ManageUsers().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_lblManageUsersMouseClicked

    private void lblManageSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageSuppliersMouseClicked
        new ManageSuppliers().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_lblManageSuppliersMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are You Sure To Logout?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lblManageCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageCustomersMouseClicked
        new ManageCustomers().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblManageCustomersMouseClicked

    private void lblProductsAndPurchasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductsAndPurchasesMouseClicked
        new ProductsAndStocks().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblProductsAndPurchasesMouseClicked

    private void lblSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesMouseClicked
        new Sales().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblSalesMouseClicked

    private void lblSalesReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesReportMouseClicked
        new SalesReport().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblSalesReportMouseClicked

    private void lblProductsAndPurchasesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductsAndPurchasesMouseEntered
        lblProductsAndPurchases.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblProductsAndPurchases.setForeground(Color.BLUE);
        lblProductsAndPurchases.setBackground(Color.red);
    }//GEN-LAST:event_lblProductsAndPurchasesMouseEntered

    private void lblProductsAndPurchasesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductsAndPurchasesMouseExited
        lblProductsAndPurchases.setForeground(new java.awt.Color(51, 102, 255));
        lblProductsAndPurchases.setBorder(null);
    }//GEN-LAST:event_lblProductsAndPurchasesMouseExited

    private void lblSalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesMouseEntered
        lblSales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSales.setForeground(Color.BLUE);
        lblSales.setBackground(Color.red);
    }//GEN-LAST:event_lblSalesMouseEntered

    private void lblSalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesMouseExited
        lblSales.setForeground(new java.awt.Color(51, 102, 255));
        lblSales.setBorder(null);
    }//GEN-LAST:event_lblSalesMouseExited

    private void lblSalesReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesReportMouseEntered
        lblSalesReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSalesReport.setForeground(Color.BLUE);
        lblSalesReport.setBackground(Color.red);
    }//GEN-LAST:event_lblSalesReportMouseEntered

    private void lblSalesReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesReportMouseExited
        lblSalesReport.setForeground(new java.awt.Color(51, 102, 255));
        lblSalesReport.setBorder(null);
    }//GEN-LAST:event_lblSalesReportMouseExited

    private void lblManageUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageUsersMouseEntered
        lblManageUsers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblManageUsers.setForeground(Color.BLUE);
        lblManageUsers.setBackground(Color.red);
    }//GEN-LAST:event_lblManageUsersMouseEntered

    private void lblManageUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageUsersMouseExited
        lblManageUsers.setForeground(new java.awt.Color(51, 102, 255));
        lblManageUsers.setBorder(null);
    }//GEN-LAST:event_lblManageUsersMouseExited

    private void lblManageSuppliersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageSuppliersMouseEntered
        lblManageSuppliers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblManageSuppliers.setForeground(Color.BLUE);
        lblManageSuppliers.setBackground(Color.red);
    }//GEN-LAST:event_lblManageSuppliersMouseEntered

    private void lblManageSuppliersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageSuppliersMouseExited
        lblManageSuppliers.setForeground(new java.awt.Color(51, 102, 255));
        lblManageSuppliers.setBorder(null);
    }//GEN-LAST:event_lblManageSuppliersMouseExited

    private void lblManageCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageCustomersMouseEntered
        lblManageCustomers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblManageCustomers.setForeground(Color.BLUE);
        lblManageCustomers.setBackground(Color.red);
    }//GEN-LAST:event_lblManageCustomersMouseEntered

    private void lblManageCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageCustomersMouseExited
        lblManageCustomers.setForeground(new java.awt.Color(51, 102, 255));
        lblManageCustomers.setBorder(null);
    }//GEN-LAST:event_lblManageCustomersMouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setForeground(Color.RED);
        jLabel5.setBackground(Color.red);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setBorder(null);
    }//GEN-LAST:event_jLabel5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblManageCustomers;
    private javax.swing.JLabel lblManageSuppliers;
    private javax.swing.JLabel lblManageUsers;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblProductsAndPurchases;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSales;
    private javax.swing.JLabel lblSalesReport;
    // End of variables declaration//GEN-END:variables
}
